theme: jekyll-theme-minimal

plugins:
- jekyll-github-metadata
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
- jemoji

markdown: kramdown
  # !github-pages! mandatory › https://help.github.com/articles/using-jekyll-with-pages/#configuration-settings-you-cannot-change
  # Since Jekyll 3 the default highlighter is Rouge (replaced Pygments.rb in v44)
highlighter: rouge

#  # More › http://kramdown.gettalong.org/quickref.html
#  # Options › http://kramdown.gettalong.org/options.html
#kramdown:
#  input:          GFM
#  # https://github.com/jekyll/jekyll/pull/4090
#  syntax_highlighter: rouge
#
#  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
#  # span, block element options fall back to global
#  syntax_highlighter_opts:
#    default_lang: groovy
#    css_class: 'highlight'
#    span:
#      line_numbers: true
#    block:
#      line_numbers: false